lst = ["one", "two", "three", "    "]
lst.append("four")
print(lst)
lst.reverse()
print(lst)
lst.append("one")
print(lst.count("one"))
print(lst)
lst.insert(2, "one")
print(lst)
lst.index("one", 0,5)
print(lst)
lst.remove("    ")
print(lst)
lst1=reversed(lst)
print(reversed(lst))